---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "cnpg-i.fullname" . }}-client
spec:
  commonName: {{ template "cnpg-i.fullname" . }}-client
  duration: 2160h
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: {{ template "cnpg-i.fullname" . }}-selfsigned-issuer
  renewBefore: 360h
  secretName: {{ include "cnpg-i.fullname" . }}-client-tls
  usages:
  - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "cnpg-i.fullname" . }}-server
spec:
  commonName: {{ template "cnpg-i.fullname" . }}
  dnsNames:
  - {{ template "cnpg-i.fullname" . }}
  duration: 2160h
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: {{ template "cnpg-i.fullname" . }}-selfsigned-issuer
  renewBefore: 360h
  secretName: {{ include "cnpg-i.fullname" . }}-server-tls
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "cnpg-i.fullname" . }}-selfsigned-issuer
spec:
  selfSigned: {}
