apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- with .Values.customLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "plugin-barman-cloud.fullname" . }}-client
spec:
  commonName: {{ include "plugin-barman-cloud.fullname" . }}-client
  duration: 2160h
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: {{ include "plugin-barman-cloud.fullname" . }}-selfsigned-issuer
  renewBefore: 360h
  secretName: {{ include "plugin-barman-cloud.fullname" . }}-client-tls
  usages:
  - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- with .Values.customLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "plugin-barman-cloud.fullname" . }}-server
spec:
  commonName: {{ include "plugin-barman-cloud.fullname" . }}
  dnsNames:
  - {{ include "plugin-barman-cloud.fullname" . }}
  duration: 2160h
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: {{ include "plugin-barman-cloud.fullname" . }}-selfsigned-issuer
  renewBefore: 360h
  secretName: {{ include "plugin-barman-cloud.fullname" . }}-server-tls
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    {{- with .Values.customLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "plugin-barman-cloud.fullname" . }}-selfsigned-issuer
spec:
  selfSigned: {}
