apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "plugin-barman-cloud.labels" . | nindent 4 }}
    {{- with .Values.customLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "plugin-barman-cloud.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "plugin-barman-cloud.selectorLabels" . | nindent 6 }}
  strategy: {{- toYaml .Values.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "plugin-barman-cloud.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      imagePullSecrets:
        {{- with .Values.imagePullSecrets }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
      - args:
        - operator
        - --server-cert=/server/tls.crt
        - --server-key=/server/tls.key
        - --client-cert=/client/tls.crt
        - --server-address=:{{ .Values.service.port }}
        - --leader-elect
        - --log-level=debug
        env:
        - name: SIDECAR_IMAGE
          value: {{ printf "%s-sidecar:%s" .Values.image.repository (.Chart.AppVersion | default .Values.image.tag) }}
        image: {{ .Values.image.repository }}:{{ .Chart.AppVersion | default .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: barman-cloud
        ports:
        - containerPort: {{ .Values.service.port }}
          protocol: TCP
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: {{ .Values.service.port }}
        resources:
          {{- with .Values.resources }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        securityContext:
          {{- with .Values.podSecurityContext }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        volumeMounts:
        - mountPath: /server
          name: server
        - mountPath: /client
          name: client
      securityContext:
        {{- with .Values.securityContext }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      serviceAccountName: {{ include "plugin-barman-cloud.serviceAccountName" . }}
      volumes:
      - name: server
        secret:
          defaultMode: 420
          secretName: {{ include "plugin-barman-cloud.fullname" . }}-server-tls
      - name: client
        secret:
          defaultMode: 420
          secretName: {{ include "plugin-barman-cloud.fullname" . }}-client-tls
      nodeSelector:
        {{- with .Values.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      affinity:
        {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      tolerations:
        {{- with .Values.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
