---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cnpg-i.fullname" . }}
  labels:
    {{- include "cnpg-i.labels" . | nindent 4 }}
    {{- with .Values.customLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "cnpg-i.selectorLabels" . | nindent 6 }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "cnpg-i.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - args:
        - operator
        - --server-cert=/server/tls.crt
        - --server-key=/server/tls.key
        - --client-cert=/client/tls.crt
        - --server-address=:{{ .Values.service.port }}
        - --leader-elect
        - --log-level=debug
        env:
        - name: SIDECAR_IMAGE
          value: {{ .Values.image.repository }}:{{ .Chart.AppVersion | default .Values.image.tag }}
        image: {{ .Values.image.repository }}:{{ .Chart.AppVersion | default .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: barman-cloud
        ports:
        - containerPort: {{ .Values.service.port }}
          protocol: TCP
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: {{ .Values.service.port }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.podSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
          - mountPath: /server
            name: server
          - mountPath: /client
            name: client
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cnpg-i.serviceAccountName" . }}
      volumes:
        - name: server
          secret:
            secretName: {{ include "cnpg-i.fullname" . }}-server-tls
        - name: client
          secret:
            secretName: {{ include "cnpg-i.fullname" . }}-client-tls
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
