apiVersion: v1
kind: Service
metadata:
  annotations:
    cnpg.io/pluginClientSecret: {{ include "plugin-barman-cloud.fullname" . }}-client-tls
    cnpg.io/pluginPort: "{{ .Values.service.port }}"
    cnpg.io/pluginServerSecret: {{ include "plugin-barman-cloud.fullname" . }}-server-tls
  labels:
    {{- include "plugin-barman-cloud.labels" . | nindent 4 }}
    {{- with .Values.customLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    cnpg.io/pluginName: plugin-barman-cloud.cloudnative-pg.io
  name: {{ include "plugin-barman-cloud.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
  selector:
    {{- include "plugin-barman-cloud.selectorLabels" . | nindent 4 }}
